### ISSUE TITLE
Wrong address offset for beggars

### ISSUE THREAD

**Issue by felixbrandt** [waldi/Anno1404Warenrechner#2]
Hello,

the tool is using the wrong memory address offset for beggars. `0x7cb8` is the amount of beggars living on the streets. The correct offset is `0x7cd8` which is the amount of beggars living in alms houses. Only beggars in alms houses need fish and most.

I will create a pull request to fix this issue. Thank you for this great piece of software! 👍

**Comment by waldi** [comment]
Hey Felix,
I was actually playing like a month ago and wondering, whether or not my beggars are counted correctly, because my supply of fish didn't seem right :D 
Thanks a lot!

**Comment by waldi** [comment]
I'm not an C# developer, so if you got bigger improvements, to also the UI, they're very welcome :)
